### Register Post Request

POST http://localhost:5000/api/users/register
content-type: application/json

{
  "name": "Merul Dhiman", 
  "email": "merul@coodos.co",
  "password": "password"
}

### User Login Post Request

POST http://localhost:5000/api/users/login
content-type: application/json

{
  "email": "merul@coodos.co",
  "password": "password"
}


### user update profile 

PUT http://localhost:5000/api/users/settings
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYjhkZTc0NWFlOTBhMmQ3MTQ0NTQyZiIsImlhdCI6MTYyMjcyOTA1MSwiZXhwIjoxNjMwNTA1MDUxfQ.Qz7AgN4jZu5HSwjK5p_fvFKrKiVzsScHky7nEEEz1J0

{
  "name": "Merul Dhiman", 
  "email": "merul@coodos.co"
}

### user update password

PUT http://localhost:5000/api/users/updatePassword
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYjhkZTc0NWFlOTBhMmQ3MTQ0NTQyZiIsImlhdCI6MTYyMjcyOTA1MSwiZXhwIjoxNjMwNTA1MDUxfQ.Qz7AgN4jZu5HSwjK5p_fvFKrKiVzsScHky7nEEEz1J0

{
  "name": "Merul Dhiman", 
  "email": "merul@coodos.co",
  "password": "123456"
}
